print("How many hours have I worked this pay period?")
print("Let's see... I've worked 8 hours every day except for one.")
print("On that day, I only worked for 5 1/2 hours.")
print("This pay period had 10 work days, so how many did I work 8 hours for?")
print("If I worked for 10 days total, then I must've worked 8 hours for", 10 - 1,"days")
print("For those", 10 - 1, "days, I worked a total of", 9 * 8, "hours")
print("Including the day I worked 5.5 hours, I worked a net total of", ((10 - 1) * 8) + (1 * 5.5), "hours!")
print("I was SUPPOSED to work", 10 * 8, "hours this week, but I only worked", ((10 - 1) * 8) + (1 * 5.5), "hours")
print("This means I am", (10 * 8) - (((10 - 1) * 8) + (1 * 5.5)), "hours short!")
